### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Redragon96** [zeel01/MonsterBlocks#229] opened 2024-03-24 12:05 UTC
Hi/good morning.
I'm contacting you about a problem with the module.
Once I download 'monster block', which I really like as a module, it asks me to install a second module on which it is dependent.
Up to here everything is ok.
Once I start the game and activate the two modules to use them they don't work.
I'm still not familiar with foundry, maybe I'm missing something simple.
Could you explain to me why please?
I have dnd5e version 3.1.0
and Monster block 3.4.0
Thank you

**Comment by zeel01** [comment] 2024-03-25 12:26
Yes, there are compatibility issues with the latest version of Foundry and the dnd5e system. I'm working on fixing these issues, but I haven't had a lot of time to work on it lately. Keep an eye on this checklist for progress: #224. When there is a release, it will also be announced in the package-releases channel of the official Foundry VTT Discord: https://discord.gg/foundryvtt.

I'm closing this issue as duplicate since I already know what the problem is.

**Closed by zeel01** 2024-03-25 12:26 UTC
Labels: duplicate
