### ISSUE TITLE
Can minimize but not re-open a block

### ISSUE THREAD

**Issue by kschutter** [zeel01/MonsterBlocks#217] opened 2023-11-03 19:42 UTC
Double clicking the title bar minimized it to just the title bar, as expected, but double clicking said title bar does not reopen the block

**Comment by niborbb** [comment] 2023-11-28 17:04
To add a little more context: If you try to reopen a sheet by double-clicking on it, it just logs the full data to the console, which means that getData() of MonsterBlock5e.js is called at some point.
This was added during the last merge by @evan-rash. Sorry for the ping, since you wrote the code for v11 support (during which you added that console log), maybe you have an idea why this is not working as intended and maybe even a possible fix?
Just to be clear, there is no error message. Apart from the aforementioned log of that sheet data in the console nothing happens when you try to reopen the minimized sheet.

**Comment by zeel01** [comment] 2024-02-03 04:08
It's re-rendering the sheet, but not changing the state for some reason. Requires more investigation.

**Comment by zeel01** [comment] 2024-02-27 03:53
Resolved via 3f70a28

**Closed by zeel01** 2024-02-27 03:53 UTC
Labels: bug, help wanted
