### ISSUE TITLE
Targeting issue when combined with MIDI QoL

### ISSUE THREAD

**Issue by grovell** [zeel01/MonsterBlocks#88] opened 2021-06-14 12:44 UTC
Selecting a target and then clicking an attack from a Monster Blocks sheet doesn't recognise the intended target, and sends out a default roll. Dragging the attack onto the actor on the canvas does work however, and even registers the target for future attacks clicked from the sheet itself.
 
I've checked the console and no errors get thrown during any part of the process(That are relevant to MIDI or MB from what I could tell). 

https://user-images.githubusercontent.com/20651766/121893863-5f7e0100-cd16-11eb-99b9-17e11a59f7a6.mp4

Hope this helps to visualise the issue better than i could put it into words.

**Comment by zeel01** [comment] 2022-02-17 20:36
This is almost certainly caused by MIDI not hooking into the event listener on this sheet. If this is still an issue, it is likely better resolved by MIDI. The markup of Monster Blocks doesn't quite match the markup of the standard sheet, which is likely why this is the case, but in most cases that is so for a reason and can't really be changed.

**Closed by zeel01** 2022-02-17 20:36 UTC
Labels: Module Compatability
