### ISSUE TITLE
Make a separate category for Bonus Actions 

### ISSUE THREAD

**Issue by Fraxinus1753** [zeel01/MonsterBlocks#71] opened 2021-03-25 14:38 UTC
Thanks for the great module! I just have a little quality-of-life suggestion, somewhat linked to issue #61. 

If it's doable, I think it would be great if Bonus Actions could be displayed as their own category, as it is in statblocks in Tasha's Cauldron of Everything. As it is now, it can be hard to see at a glance which features can be activated as an action and which can be activated as a bonus action, as it needs to be written in the feature's description.

**Comment by zeel01** [comment] 2021-03-25 14:44
This is already a "maybe" feature. The issue is, that book is as far as I know the first instance of this format.

As you noticed, the current format is also wrong as issue 61 points out. But my concern is that 99% of Stat blocks with bonus actions don't list them that way, which will be weird for anyone expecting Monster Manual consistent formatting.

I will *probably* do this anyway, and use TCoE as an excuse. I do *prefer* it, as it's more clear.

**Comment by Fraxinus1753** [comment] 2021-03-26 09:24
Alright, thanks for the quick reply! I absolutely understand your point. I would just add that in my opinion - and the reason why I use your very good module - the main advantage is not so much that it looks like official statblocks, but that you have all the relevant info at a glance (which is however kind of the point of official stat blocks in the first place). 

In this regard, having bonus actions as a separate category is, I think, very helpful. I'm surprised that the official statblocks didn't do it in the first place as it forces the GM to check every description to remember what monsters can use as a bonus action. And given that GMs are already likely to forget those in the first place (at least I know I am), I find this an unfortunate design decision.

I think however that it can be explained by the fact that in a lot of those earlier statblocks, bonus actions were conditional and mostly tied to specific traits, like "if the creature reduces someone to 0 hit points, it can attack again as a bonus action", or "if the creature moves more that 20 feet, it can attack as a bonus action". Those sort of make sense to list under "Feature" (although I still think it would be more practical to have them listed under a "Bonus Action" category). However, for bonus actions that monsters can use every round no matter what (like Fey Spirits in TCE), it really makes sense to have a specific category, especially if your monster has many bonus actions from which he can choose. And I think that people designing their own monsters will tend to give them more bonus actions that regular monsters to spice things up, following advice from people like Matt Colville with his action oriented monsters (at least that's what I do). For such monsters, having a dedicated Bonus Action category is invaluable in combat. 

Finally, if you don't implement this new category, a helpful alternative would be to have the option for the type of action used to show up somewhere automatically at the beginning of the description, a bit like auto-generated attack description, from the dedicated field in Foundry. As it is now, and unless I am mistaken, you have to manually write in the description of the action that it uses a bonus action. 

So that was my point of view, but I'll of course understand whichever decision you make! Sorry for the wall of text and thanks again for this great module!

**Comment by zeel01** [comment] 2021-06-21 19:40
Closing as duplicate of https://github.com/zeel01/MonsterBlocks/issues/61 to consolidate issues.

**Closed by zeel01** 2021-06-21 19:40 UTC
Labels: duplicate, enhancement
